E-Kitap/Controllers/TagController.cs
using E_Kit.Data.Entities;
using E_Kit.Service.TagService;
using E_Kitap.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Kitap.Controllers
{
    [Auth]
    public class TagController : Controller
    {
        // GET: Tag
        private readonly TagService _tagService = new TagService();
        public ActionResult Index()
        {
            return View(_tagService.GetTagList());
        }
        public ActionResult Create()
        {
            return View(new Tags { IsActive = true });
        }
        [HttpPost]
        public ActionResult Create(Tags model, string favcolor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.ColorCode = favcolor;
                    _tagService.InsertTag(model);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                var ex = e.Message;

            }
            return View();
        }
        public ActionResult Edit(int id)
        {
        
            return View(_tagService.FindTagById(id));
        }

        [HttpPost]
        public ActionResult Edit(Tags model, string favcolor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.ColorCode = favcolor;
                    _tagService.EditTag(model);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                var ex = e.Message;               
            }
            return View();
        }


        public ActionResult Delete(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _tagService.DeleteTag(id);
                }
            }
            catch (Exception e)
            {
                var ex = e.Message;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

E-Kitap/Views/Tag/Create.cshtml
@model E_Kit.Data.Entities.Tags
@{
    ViewBag.Title = "Etiket Ekle";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Etiket <small>ekle</small></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Create", "Tag", FormMethod.Post))
                    {
                        @Html.ValidationSummary()
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Türkçe Ad</label>
                            @Html.TextBoxFor(model => model.NameTr, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">İngilizce Ad</label>
                            @Html.TextBoxFor(model => model.NameEn, new { @class = "form-control" })
                        </div>
                        <div class="form-inline col-sm-12">
                            <label class="col-form-label">Etiket rengi</label>&nbsp;&nbsp;&nbsp;
                            <input type="color" class="col-sm-1" name="favcolor" id="favcolor" value="#ff0000">
                        </div>
                        <div class="form-inline col-sm-12">
                            <label class="col-form-label">Aktif Et</label>
                            @Html.CheckBoxFor(model => model.IsActive, new { @class = "col-sm-1 form-control icheckbox_square-green" })
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary btn-sm" type="submit">Kaydet</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {

    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/iCheck")
}

E-Kitap/Views/Tag/Edit.cshtml
@model E_Kit.Data.Entities.Tags
@{
    ViewBag.Title = "Etiket Düzenle";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Etiket <small>düzenle</small></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Edit", "Tag", FormMethod.Post))
                    {
                        @Html.ValidationSummary()
                        @Html.HiddenFor(x => x.Id);
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Türkçe Ad</label>
                            @Html.TextBoxFor(model => model.NameTr, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">İngilizce Ad</label>
                            @Html.TextBoxFor(model => model.NameEn, new { @class = "form-control" })
                        </div>
                        <div class="form-inline col-sm-12">
                            <label class="col-form-label">Etiket rengi</label>&nbsp;&nbsp;&nbsp;
                            <input type="color" class="col-sm-1" name="favcolor" id="favcolor" value="@Model.ColorCode">
                        </div>
                        <div class="form-inline col-sm-12">
                            <label class="col-form-label">Aktif Et</label>
                            @Html.CheckBoxFor(model => model.IsActive, new { @class = "col-sm-1 form-control icheckbox_square-green" })
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary btn-sm" type="submit">Kaydet</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {

    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/iCheck")
}

E-Kitap/Views/Tag/Index.cshtml
@model IEnumerable<E_Kit.Data.Entities.Tags>
@{
    ViewBag.Title = "Etiket Listesi";
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Etiketler</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <table class="table table-striped table-bordered table-hover dataTables">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Türkçe Ad</th>                  
                                <th>Etiket Rengi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var tags in Model)
                            {
                            <tr>
                                <td>
                                    <a class="btn btn-info  dim" href="/Tag/Edit/@tags.Id"><i class="fa fa-paste"></i>Düzenle</a>
                                    <a class="btn btn-warning  dim" href="/Tag/Delete/@tags.Id"><i class="fa fa-trash"></i>Sil</a>
                                </td>
                                <td>@tags.NameTr</td>
                                <td>@tags.ColorCode</td>
                            </tr>
                            }
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>


@section Styles {
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/dataTables")

    <script type="text/javascript">
        $(document).ready(function () {

            $('.dataTables').DataTable({
                 "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Turkish.json"
                },
                pageLength: 25,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy' },
                    { extend: 'csv' },
                    { extend: 'excel', title: 'ExampleFile' },
                    { extend: 'pdf', title: 'ExampleFile' },

                    {
                        extend: 'print',
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                        }
                    }
                ]

            });



        });

    </script>
}