E-Kitap/Controllers/SettingController.cs
using E_Kit.Data.Entities;
using E_Kit.Service.SettingService;
using E_Kitap.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Kitap.Controllers
{
    [Auth]
    public class SettingController : Controller
    {
        private readonly SettingService _settingService = new SettingService();
        // GET: Setting
        public ActionResult Edit()
        {
            return View(_settingService.GetSetting());
        }

        [HttpPost]
        public ActionResult Edit(Setting model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _settingService.EditSetting(model);
                    return RedirectToAction("Index","Home");
                }
            }
            catch (Exception e)
            {
                var ex = e.Message;                
            }
            return View();
        }
    }
}

E-Kitap/Views/Setting/Edit.cshtml
@model E_Kit.Data.Entities.Setting
@{
    ViewBag.Title = "Ayarlar";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Ayarlar</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Edit", "Setting", FormMethod.Post))
                    {
                        @Html.ValidationSummary()
                        @Html.HiddenFor(x => x.Id);
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">E-mail Adresi</label>
                            @Html.TextBoxFor(model => model.EmailAddress, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Şifre</label>
                            @Html.PasswordFor(model => model.EmailPassword, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Host</label>
                            @Html.TextBoxFor(model => model.EmailHost, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Port</label>
                            @Html.TextBoxFor(model => model.EmailPort, new { @class = "form-control", @type = "number", @min = "0" })
                        </div>
                        <div class="form-inline col-sm-12">
                            <label class="col-form-label">SSL</label>
                            @Html.CheckBoxFor(model => model.EmailSsl, new { @class = "col-sm-1 form-control icheckbox_square-green" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Facebook URL</label>
                            @Html.TextBoxFor(model => model.SocialFacebookUrl, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Instagram URL</label>
                            @Html.TextBoxFor(model => model.SocialInstagramUrl, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Linkedin URL</label>
                            @Html.TextBoxFor(model => model.SocialLinkedinUrl, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Twitter URL</label>
                            @Html.TextBoxFor(model => model.SocialTwitterUrl, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Youtube URL</label>
                            @Html.TextBoxFor(model => model.SocialYoutubeUrl, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Varsayılan kiralama süresi</label>
                            @Html.TextBoxFor(model => model.DefaultRentalTermDay, new { @class = "form-control", @type = "number", @min = "0" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">IOS Max Version</label>
                            @Html.TextBoxFor(model => model.IosMaxVersion, new { @class = "form-control", @type = "number", @min = "0" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Android Max Version</label>
                            @Html.TextBoxFor(model => model.AndroidMaxVersion, new { @class = "form-control", @type = "number", @min = "0" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Varsayılan Site URL'i</label>
                            @Html.TextBoxFor(model => model.BaseWebSiteUrl, new { @class = "form-control" })
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary btn-sm" type="submit">Kaydet</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {

    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/iCheck")
}