E-Kitap/Controllers/SitePageController.cs
using E_Kit.Data.Entities;
using E_Kit.Service.SitePageService;
using E_Kitap.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Kitap.Controllers
{
    [Auth]
    public class SitePageController : Controller
    {
        private readonly AboutApplicationService _aboutApplicationService = new AboutApplicationService();
        private readonly PrivacyPolicyService _privacyPolicyService = new PrivacyPolicyService();
        private readonly ContactService _contactService = new ContactService();
        // GET: SitePage
        
        public ActionResult AboutApplication()
        {
            return View(_aboutApplicationService.GetAboutApplication());
        }
        [HttpPost]
        public ActionResult AboutApplication(AboutApplication model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _aboutApplicationService.EditAboutApplication(model);
                    return RedirectToAction("AboutApplication");
                }
            }
            catch (Exception e)
            {
                var ex = e.Message;
            }
            return View();
        }
        public ActionResult PrivacyPolicy()
        {
            return View(_privacyPolicyService.GetPrivacyPolicy());
        }
        [HttpPost]
        public ActionResult PrivacyPolicy(PrivacyPolicy model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _privacyPolicyService.EditPrivacyPolicy(model);
                    return RedirectToAction("PrivacyPolicy");
                }
            }
            catch (Exception e)
            {
                var ex = e.Message;
            }
            return View();
        }
        public ActionResult Contact()
        {
            return View(_contactService.GetContact());
        }
        [HttpPost]
        public ActionResult Contact(Contact model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contactService.EditContact(model);
                    return RedirectToAction("Contact");
                }
            }
            catch (Exception e)
            {
                var ex = e.Message;
            }
            return View();
        }
    }
}

E-Kitap/Views/SitePage/AboutApplication.cshtml
@model E_Kit.Data.Entities.AboutApplication
@{
    ViewBag.Title = "Hakkımızda Sayfası Düzenle";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Hakkımızda Sayfası <small>düzenle</small></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("AboutApplication", "SitePage", FormMethod.Post))
                    {
                    <div class="form-group">
                        <label class="col-sm-2 col-form-label">Türkçe İçerik</label>
                        @Html.TextAreaFor(m => m.TextTr,new { id = "editor"})
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 col-form-label">İngilizce İçerik</label>
                        @Html.TextAreaFor(m => m.TextEn, new { id = "editor2" })
                    </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary btn-sm" type="submit">Kaydet</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#editor'))
            .then(editor => {
                console.log(editor);
            })
            .catch(error => {
                console.error(error);
            });

         ClassicEditor
            .create(document.querySelector('#editor2'))
            .then(editor => {
                console.log(editor);
            })
            .catch(error => {
                console.error(error);
            });
    </script>
}

E-Kitap/Views/SitePage/Contact.cshtml
@model E_Kit.Data.Entities.Contact
@{
    ViewBag.Title = "İletişim Sayfası Düzenle";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>İletişim Sayfası <small>düzenle</small></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Contact", "SitePage", FormMethod.Post))
                    {
                        @Html.ValidationSummary()
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Telefon</label>
                            @Html.TextBoxFor(model => model.Tel, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">E-mail</label>
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Adres</label>
                            @Html.TextAreaFor(model => model.Address, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Lokasyon</label>
                            @Html.TextBoxFor(model => model.Location, new { @class = "form-control" })
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary btn-sm" type="submit">Kaydet</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

E-Kitap/Views/SitePage/PrivacyPolicy.cshtml
@model E_Kit.Data.Entities.PrivacyPolicy
@{
    ViewBag.Title = "Gizlilik Politikası Sayfası Düzenle";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Gizlilik Politikası Sayfası <small>düzenle</small></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("PrivacyPolicy", "SitePage", FormMethod.Post))
                    {
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">Türkçe İçerik</label>
                            @Html.TextAreaFor(m => m.TextTr, new { id = "editor" })
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-form-label">İngilizce İçerik</label>
                            @Html.TextAreaFor(m => m.TextEn, new { id = "editor2" })
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary btn-sm" type="submit">Kaydet</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#editor'))
            .then(editor => {
                console.log(editor);
            })
            .catch(error => {
                console.error(error);
            });

         ClassicEditor
            .create(document.querySelector('#editor2'))
            .then(editor => {
                console.log(editor);
            })
            .catch(error => {
                console.error(error);
            });
    </script>
}